module.exports = {
  env: {
    es6: true,
    node: true,
  },
  plugins: ["import"],
  extends: "eslint:recommended",
  parser: "babel-eslint",
  parserOptions: {
    sourceType: "module",
    ecmaVersion: 6,
    ecmaFeatures: {
      experimentalObjectRestSpread: true,
    },
  },
  rules: {
    "array-callback-return": "error",
    "arrow-body-style": [
      "error",
      "as-needed",
      { requireReturnForObjectLiteral: true },
    ],
    "arrow-parens": ["error", "as-needed"],
    "comma-dangle": ["error", "only-multiline"],
    "comma-style": "error",
    "dot-notation": "error",
    eqeqeq: "error",
    "import/first": "error",
    "import/prefer-default-export": "error",
    indent: 0,
    "linebreak-style": ["error", "unix"],
    "new-cap": ["error", { newIsCap: true, capIsNew: false }],
    "no-array-constructor": "error",
    "no-case-declarations": "off",
    "no-confusing-arrow": "error",
    "no-console": "off",
    "no-dupe-class-members": "error",
    "no-duplicate-imports": "error",
    "no-eval": "error",
    "no-iterator": "error",
    "no-loop-func": "error",
    "no-nested-ternary": "error",
    "no-new-func": "error",
    "no-new-object": "error",
    "no-param-reassign": "error",
    "no-plusplus": "error",
    "no-restricted-syntax": "error",
    "no-undef": "error",
    "no-unneeded-ternary": "error",
    "no-unused-vars": "off",
    "no-useless-constructor": "error",
    "no-useless-escape": "error",
    "no-var": "error",
    "object-shorthand": "error",
    "one-var": ["error", { let: "never", const: "never" }],
    "prefer-arrow-callback": "error",
    "prefer-const": "error",
    "prefer-rest-params": "error",
    "prefer-spread": "error",
    "prefer-template": "error",
    quotes: ["error", "double"],
    semi: "error",
    semi: ["error", "always"],
    "spaced-comment": "error",
    "template-curly-spacing": "error",
  },
};
